name: Upload 1
run-name: ${{ github.actor }} is testing UPDATE artifact with GitHub Actions
on: [push]

env:
  # github.workspace !=   GITHUB_WORKSPACE
  # github.workspace /home/runner/work/<REPO_NAME>/<REPO_NAME>
  # github.workspace /home/runner/work/hello-world/hello-world/output
  GITHUB_WORKSPACE: /home/natalia/github.com/workspace/hello-world

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name : Check out repository code
        uses : actions/checkout@v3

      - name: Build artifact
        uses: actions/upload-artifact@v3
        with:
          name: astro-docu
          path: ${{ github.workspace }}/_artifact/pages
          retention-days: 20

  release-artifact:
    runs-on : ubuntu-latest
    needs: build-artifact
    steps :
      - name : Download artifact
        uses : actions/download-artifact@v3
        with :
          name : astro-docu
          #path in case change the output
          path: ${{ GITHUB_WORKSPACE }}/output

      - name : Check files
        run: ls -R  ${{ GITHUB_WORKSPACE }}/output
