name: Upload 1
run-name: ${{ github.actor }} is testing UPDATE artifact with GitHub Actions
on: [push]
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name : Check out repository code
        uses : actions/checkout@v3
      # Update/Create artifact
      - name: Build artifact
        uses: actions/upload-artifact@v3
        with:
          name: astro-docu
          path: ${{ github.workspace }}/_artifact/pages
          retention-days: 20

  release-artifact:
    runs-on : ubuntu-latest
    needs: build-artifact
    steps :
      - name : Download artifact
        uses : actions/download-artifact@v3
        with :
          name : astro-docu
          #path in case change the output
          path: output

      - name : Check files
        run: ls -R  output
